packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"
  - "examples/basic-typescript/agent"
  - "examples/basic-typescript/app"
  - "examples/basic-python/agent"
  - "examples/basic-python/app"
  - "examples/consumers/*"

catalog:
  "@types/node": 24.13.3
  typescript: 7.0.2
