import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { IncomingMessage, ServerResponse } from "node:http";
import { syncBuiltinESMExports } from "node:module";
import { Socket } from "node:net";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";

import { scopedAuthorization, startAuthenticatedOrigin } from "./helpers/authenticated-origin.ts";
import { createStaticOriginHandler, startStaticOrigin } from "./helpers/static-host.ts";

test("static origins return usable IPv4, hostname, and IPv6 URLs", async (context) => {
  const root = await mkdtemp(resolve(tmpdir(), "remote-skills-static-address-"));
  context.after(() => rm(root, { recursive: true, force: true }));
  const pathname = "/.well-known/agent-skills/index.json";
  const catalog = '{"skills":[]}';
  await mkdir(resolve(root, ".well-known/agent-skills"), { recursive: true });
  await writeFile(resolve(root, `.${pathname}`), catalog);

  for (const [host, expectedHostname] of [
    ["127.0.0.1", "127.0.0.1"],
    ["localhost", "localhost"],
    ["::1", "[::1]"],
  ] as const) {
    await context.test(host, { timeout: 5000 }, async (subtest) => {
      let origin: Awaited<ReturnType<typeof startStaticOrigin>>;
      try {
        origin = await startStaticOrigin({ root, host });
      } catch (error) {
        if (
          host === "::1" &&
          error instanceof Error &&
          "code" in error &&
          (error.code === "EADDRNOTAVAIL" || error.code === "EAFNOSUPPORT")
        ) {
          subtest.skip("IPv6 loopback is unavailable on this platform");
          return;
        }
        throw error;
      }
      try {
        const url = new URL(origin.origin);
        assert.equal(url.protocol, "http:");
        assert.equal(url.hostname, expectedHostname);
        assert.ok(Number(url.port) > 0);
        const response = await fetch(new URL(pathname, url));
        assert.equal(response.status, 200);
        assert.equal(await response.text(), catalog);
      } finally {
        await origin.close();
      }
    });
  }
});

test("static origins serve only canonical generated resources with matching authorization", async (context) => {
  const root = await mkdtemp(resolve(tmpdir(), "remote-skills-static-host-"));
  context.after(() => rm(root, { recursive: true, force: true }));
  const directory = ".well-known/agent-skills";
  const catalogPath = `/${directory}/index.json`;
  const catalog = '{"skills":[]}';
  const artifact = Buffer.from("Example artifact bytes\n");
  const digest = createHash("sha256").update(artifact).digest("hex");
  const artifactPaths = ["md", "tar.gz", "zip"].map(
    (extension) => `/${directory}/artifacts/sha256-${digest}.${extension}`,
  );
  await mkdir(resolve(root, directory, "artifacts"), { recursive: true });
  await writeFile(resolve(root, directory, "index.json"), catalog);
  await writeFile(resolve(root, "readme.txt"), "Unserved deployment notes");
  for (const pathname of artifactPaths) {
    await writeFile(resolve(root, `.${pathname}`), artifact);
  }

  await context.test("public serving selects the intended generated bytes", async () => {
    const authorizedPaths: string[] = [];
    const origin = await startStaticOrigin({
      root,
      authorize: ({ pathname }) => {
        authorizedPaths.push(pathname);
        return undefined;
      },
    });
    try {
      const response = await fetch(`${origin.origin}${catalogPath}?view=current`);
      assert.equal(response.status, 200);
      assert.equal(response.headers.get("cache-control"), "no-cache");
      assert.equal(await response.text(), catalog);
      for (const pathname of artifactPaths) {
        const response = await fetch(`${origin.origin}${pathname}`);
        assert.equal(response.status, 200);
        assert.equal(response.headers.get("cache-control"), "public, max-age=31536000, immutable");
        assert.deepEqual(Buffer.from(await response.arrayBuffer()), artifact);
      }
      assert.equal((await fetch(`${origin.origin}/readme.txt`)).status, 404);
      assert.deepEqual(authorizedPaths, [catalogPath, ...artifactPaths]);
    } finally {
      await origin.close();
    }
  });

  await context.test("private catalogs and every artifact require authorization", async () => {
    const token = randomUUID();
    const headers = { Authorization: `Bearer ${token}` };
    const origin = await startAuthenticatedOrigin({ root, token });
    try {
      const catalogUrl = `${origin.origin}${catalogPath}`;
      assert.equal((await fetch(catalogUrl)).status, 401);
      assert.equal((await fetch(catalogUrl, { headers })).status, 403);
      const catalogResponse = await fetch(catalogUrl, {
        headers: { ...headers, "Remote-Skills-Scope": "engineering" },
      });
      assert.equal(catalogResponse.status, 200);
      assert.equal(catalogResponse.headers.get("remote-skills-scope"), "engineering");
      assert.equal(await catalogResponse.text(), catalog);
      for (const pathname of artifactPaths) {
        const url = `${origin.origin}${pathname}`;
        assert.equal((await fetch(url)).status, 401);
        const response = await fetch(url, { headers });
        assert.equal(response.status, 200);
        assert.equal(response.headers.get("cache-control"), "private, no-store");
        assert.deepEqual(Buffer.from(await response.arrayBuffer()), artifact);
      }
      assert.equal((await fetch(`${origin.origin}/readme.txt`)).status, 404);
      assert.equal((await fetch(`${origin.origin}/readme.txt`, { headers })).status, 404);
    } finally {
      await origin.close();
    }
  });
});

test("the private authorization callback denies an unknown resource", () => {
  const socket = new Socket();
  try {
    const request = new IncomingMessage(socket);
    const authorize = scopedAuthorization({ token: randomUUID(), scope: "engineering" });
    assert.deepEqual(authorize({ pathname: "/readme.txt", request }), { status: 403 });
  } finally {
    socket.destroy();
  }
});

test("static serving rejects linked deployment entries before opening them", async (context) => {
  const root = await mkdtemp(resolve(tmpdir(), "remote-skills-static-policy-"));
  context.after(() => rm(root, { recursive: true, force: true }));
  const pathname = `/.well-known/agent-skills/artifacts/sha256-${"a".repeat(64)}.md`;
  const target = resolve(root, `.${pathname}`);
  await mkdir(resolve(root, ".well-known/agent-skills/artifacts"), { recursive: true });
  await writeFile(target, "Ordinary example bytes\n");
  const originalLstat = fs.promises.lstat;
  const originalOpen = fs.promises.open;
  const entries = [
    root,
    resolve(root, ".well-known"),
    resolve(root, ".well-known/agent-skills"),
    resolve(root, ".well-known/agent-skills/artifacts"),
    target,
  ];
  for (const [index, entry] of entries.entries()) {
    await context.test(`linked tree entry ${index} is unavailable`, async (subtest) => {
      const visited: string[] = [];
      let opened = 0;
      subtest.mock.method(fs.promises, "lstat", async (path: fs.PathLike) => {
        visited.push(String(path));
        const metadata = await originalLstat(path);
        if (String(path) === entry) metadata.isSymbolicLink = () => true;
        return metadata;
      });
      subtest.mock.method(
        fs.promises,
        "open",
        async (path: fs.PathLike, flags: string | number) => {
          opened += 1;
          return originalOpen(path, flags);
        },
      );
      syncBuiltinESMExports();
      subtest.after(() => {
        subtest.mock.restoreAll();
        syncBuiltinESMExports();
      });
      const socket = new Socket();
      try {
        const request = new IncomingMessage(socket);
        request.method = "HEAD";
        request.url = pathname;
        const response = new ServerResponse(request);
        await createStaticOriginHandler({ root })(request, response);
        assert.equal(response.statusCode, 404);
        assert.equal(opened, 0);
        assert.deepEqual(visited, entries.slice(0, index + 1));
        if (entry === root) {
          await assert.rejects(startStaticOrigin({ root }), /unlinked directory/u);
        }
      } finally {
        socket.destroy();
      }
    });
  }
  await context.test("a multiply linked regular entry is unavailable", async (subtest) => {
    subtest.mock.method(fs.promises, "lstat", async (path: fs.PathLike) => {
      const metadata = await originalLstat(path);
      if (String(path) === target) metadata.nlink = 2;
      return metadata;
    });
    syncBuiltinESMExports();
    subtest.after(() => {
      subtest.mock.restoreAll();
      syncBuiltinESMExports();
    });
    const socket = new Socket();
    try {
      const request = new IncomingMessage(socket);
      request.method = "HEAD";
      request.url = pathname;
      const response = new ServerResponse(request);
      await createStaticOriginHandler({ root })(request, response);
      assert.equal(response.statusCode, 404);
    } finally {
      socket.destroy();
    }
  });
});

test("static serving closes retained handles on HEAD and ordinary response failures", async (context) => {
  const root = await mkdtemp(resolve(tmpdir(), "remote-skills-static-lifecycle-"));
  context.after(() => rm(root, { recursive: true, force: true }));
  const pathname = "/.well-known/agent-skills/index.json";
  const catalog = '{"skills":[]}';
  await mkdir(resolve(root, ".well-known/agent-skills"), { recursive: true });
  await writeFile(resolve(root, `.${pathname}`), catalog);
  const originalOpen = fs.promises.open;
  for (const phase of ["HEAD", "metadata", "headers", "stream-start", "stream", "GET"] as const) {
    await context.test(phase, { timeout: 5000 }, async (subtest) => {
      const handles: fs.promises.FileHandle[] = [];
      const closures: Promise<void>[] = [];
      const failure = new Error("ordinary injected I/O failure");
      subtest.mock.method(
        fs.promises,
        "open",
        async (path: fs.PathLike, flags: string | number) => {
          assert.equal(typeof flags, "number");
          if (typeof flags === "number")
            assert.equal(flags & fs.constants.O_NOFOLLOW, fs.constants.O_NOFOLLOW);
          const handle = await originalOpen(path, flags);
          handles.push(handle);
          const closed = Promise.withResolvers<void>();
          closures.push(closed.promise);
          const originalClose = handle.close.bind(handle);
          subtest.mock.method(handle, "close", async () => {
            await originalClose();
            closed.resolve();
          });
          if (phase === "metadata")
            subtest.mock.method(handle, "stat", async () => {
              throw failure;
            });
          if (phase === "stream-start")
            subtest.mock.method(handle, "createReadStream", () => {
              throw failure;
            });
          if (phase === "stream") {
            const originalStream = handle.createReadStream.bind(handle);
            subtest.mock.method(handle, "createReadStream", () => {
              const stream = originalStream();
              queueMicrotask(() => stream.destroy(failure));
              return stream;
            });
          }
          return handle;
        },
      );
      syncBuiltinESMExports();
      subtest.after(() => {
        subtest.mock.restoreAll();
        syncBuiltinESMExports();
      });
      if (phase === "GET" || phase === "HEAD") {
        const origin = await startStaticOrigin({ root });
        try {
          const response = await fetch(`${origin.origin}${pathname}`, { method: phase });
          assert.equal(response.status, 200);
          assert.equal(response.headers.get("content-length"), String(catalog.length));
          assert.equal(await response.text(), phase === "HEAD" ? "" : catalog);
          await Promise.all(closures);
        } finally {
          await origin.close();
        }
      } else {
        const socket = new Socket();
        try {
          const request = new IncomingMessage(socket);
          request.method = phase === "stream" || phase === "stream-start" ? "GET" : "HEAD";
          request.url = pathname;
          const response = new ServerResponse(request);
          if (phase === "headers")
            subtest.mock.method(response, "writeHead", () => {
              throw failure;
            });
          const operation = createStaticOriginHandler({ root })(request, response);
          await assert.rejects(operation, (error) => error === failure);
        } finally {
          socket.destroy();
        }
      }
      assert.equal(handles.length, 1);
      assert.equal(handles[0]?.fd, -1);
    });
  }
});
